version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/amazon-kinesis-kafka-connecter-*.jar
  name: amazon-kinesis-kafka-connecter-$(cat pom.xml | grep version -m 1 | sed 's/<version>//' | sed 's/<\/version>//' | tr -d '[:blank:]')
